### ISSUE TITLE
BUG: same items/blocks broken with different things do not stack

### ISSUE THREAD

**Issue by Michepoli** [Reaviik/Infinity-Nexus-Mod-1.20.1#1]
Breaking a block or an item with a tool will drop it and make it unstackable with the same block/item collected by using another tool.
Affects every item in the game and from other mods!
![365329282-e53b1b33-d087-48f8-b57a-30365d2114fb](https://github.com/user-attachments/assets/b19711c6-b502-4281-949c-093afd73b10e)
 Using latest version of forge and 1.20.1

**Comment by Reaviik** [comment]
I can't replicate the bug, what tool are you using to collect the blocks/item, what specifically are you using so that the items end up having nbt?

**Comment by Michepoli** [comment]
Tools (vanilla and modded (redstone arsenal or thermal)) and hand

**Comment by Michepoli** [comment]
maybe its a conflict with some mods since its in a modpack, i just tested and blocks and items stacks like normal without the mod

**Comment by Reaviik** [comment]
which is very strange because I just downloaded your modpack to try to replicate it and it's all piling up

**Comment by Michepoli** [comment]
Ok this is weird

**Comment by Michepoli** [comment]
https://github.com/user-attachments/assets/9a598028-dba6-47a4-bc7b-11a201ab8fad

this is a clip on what happens

**Comment by Reaviik** [comment]
it really happens, but only if you take 1 single block, if you take several at once so that there is no content, it's as if the first item of that type in the inventory was modified, I'll try to update the forge version and do some tests, in version that the mod is made in, this doesn't count, however in the version you are using it really works.

**Comment by Michepoli** [comment]
The version of the pack available on curseforge uses an old version of the mod, i updated it to the latest and it still happens like in the clip

**Comment by Reaviik** [comment]
I discovered what was causing the error, I was trying to get a tag before it was generated, it is already fixed and available in version 3.1.1

Thanks for reporting <3

**Comment by Michepoli** [comment]
Thanks to you!
![immagine](https://github.com/user-attachments/assets/6fde19b8-2074-4fd3-82ac-307ee9fb6630)
I insisted cause your mod plays quite an important role in the pack as you can see (final chapter!)
